import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Toaster } from 'react-hot-toast';
import { ThemeProvider } from 'next-themes'; // ✅ ১. ThemeProvider ইম্পোর্ট করুন

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning // ✅ ২. Hydration Warning এড়াতে এটি যোগ করুন
    >
      <body className="min-h-full flex flex-col">
        {/* ✅ ৩. ThemeProvider দিয়ে পুরো অ্যাপ র‍্যাপ করুন */}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster position="top-center" reverseOrder={false} />
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}